YourBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("blog/", include("blog.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# Urls for Blog App

from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("postComment", views.postComment, name="postComment"),
    path("", views.blogHome, name="blogHome"),
    path("<str:category>", views.blogCat, name="blogHome"),
    path("<str:category>/<str:slug>", views.blogPost, name="blogPost")
]

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    serial_no = models.AutoField(primary_key=True)
    title = models.CharField(max_length=120, null=False)
    tagline = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, null=False)
    author = models.CharField(max_length=50, null=False)
    category = models.CharField(max_length=20, default="", null=False)
    content = models.TextField()
    thumbnail_image = models.ImageField(upload_to = "blog", blank= True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return self.title + " by " + self.author

class BlogComment(models.Model):
    serial_no = models.AutoField(primary_key=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete= models.CASCADE)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(default=now)
    

blog/forms.py
from django import forms

class ImageForm(forms.Form):
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={"hidden":True}))

blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Post, BlogComment
from django.contrib import messages
from blog.templatetags import extras
# Create your views here.

def blogHome(request):
    post = Post.objects.all()
    print(post)
    context = {"posts":post, "categories":post}
    return render(request, "blog/blogHome.html", context)

def blogCat(request, category):
    post = Post.objects.filter(category=category)
    categories = Post.objects.all()
    print(post)
    context = {"posts":post, "categories":categories}
    return render(request, "blog/blogHome.html", context)

def blogPost(request, category, slug):
    post = Post.objects.filter(slug= slug, category=category).first()
    comments = BlogComment.objects.filter(post=post, parent=None)
    replies = BlogComment.objects.filter(post=post).exclude(parent=None)
    replyDict = {}
    for reply in replies:
        if reply.parent.serial_no not in replyDict.keys():
            replyDict[reply.parent.serial_no] = [reply]
        else:
            replyDict[reply.parent.serial_no].append(reply)
    context = {"post":post, "comments":comments, "replyDict":replyDict}
    return render(request, "blog/post.html", context)

def postComment(request):
    if request.method == "POST":
        comment = request.POST.get("comment-textarea")
        user = request.user
        postSerial = request.POST.get("postSerial")
        parentSerial = request.POST.get("parentSerial")
        print(parentSerial)
        post = Post.objects.get(serial_no = postSerial)

        if parentSerial == "":
            comment = BlogComment(comment= comment, user=user, post=post)
            comment.save()
            messages.success(request, "Your Comment has been Sent !!")
            return redirect(f"/blog/{post.category}/{post.slug}#comment-b")

        else:
            parentComment = BlogComment.objects.get(serial_no= parentSerial)
            comment = BlogComment(comment= comment, user=user, post=post, parent=parentComment)
            comment.save()
            messages.success(request, "Your Reply has been Sent !!")
            return redirect(f"/blog/{post.category}/{post.slug}#reply-b{parentSerial}")

    return redirect(f"/blog/{post.category}/{post.slug}")

templates/blog/blogHome.html
{% extends 'base.html' %}

{% block title %} All Blogs - YourBlog{% endblock title %}

{% block blogactive %} active {% endblock blogactive %}

{% load static %}

{% block body %}
<div class="container nth-child">
  <div class="blog-container" id="all_post">
    <div class="all-posts-heading flex-center lg-heading">All Posts</div>

    <div class="category-navbar">
      <ul class="category-item-div flex">
        <li class="category-item">
          <a href="/blog" style="color: gold;">All</a>
        </li>
        {% for cat in categories %}
        <li class="category-item">
          <a href="/blog/{{cat.category}}" class="">{{cat.category|title}}</a>
        </li>
        {% endfor %}
      </ul>
    </div>

    {% for post in posts %}

    {% if forloop.counter|divisibleby:2 %}
    <div class="blog-post-div flex-center" style="margin-top: 25px">
      <div class="blog-img-div" style="order: 2;">
        <a href="/blog/{{post.category}}/{{post.slug}}"
          ><img src="/media/{{post.thumbnail_image}}" alt="Blog Post Image"
        /></a>
      </div>

      <div class="blog-content-div flex-column-no-center" style="order: 1;">
        <div class="blog-author-div flex">
          <div class="blog-author-img">
            <img
              src="{% static 'home/img/your-blog-header1.jpg' %}"
              alt="Author's Image"
            />
          </div>

          <div class="blog-author-text">
            <p>{{post.author}}</p>
            <p>Apr 15 - 3 Min</p>
          </div>
        </div>

        <div class="blog-content">
          <a href="/blog/{{post.category}}/{{post.slug}}" style="color: black"
            ><h2 class="md-heading">{{post.title}}</h2></a
          >
          <p>{{post.content|safe|truncatechars:200}}</p>

          <div class="hr-bottom"></div>

          <div class="views-comment flex">
            <p>4356 Views</p>
            <p><a href="/blog/{{post.category}}/{{post.slug}}#comment-b">Write a comment</a></p>
          </div>
        </div>
      </div>
    </div>

    {% else %}

    <div class="blog-post-div flex-center" style="margin-top: 25px;">
      <div class="blog-img-div">
        <a href="/blog/{{post.category}}/{{post.slug}}"
          ><img src="/media/{{post.thumbnail_image}}" alt="Blog Post Image"
        /></a>
      </div>

      <div class="blog-content-div flex-column-no-center">
        <div class="blog-author-div flex">
          <div class="blog-author-img">
            <img
              src="{% static 'home/img/your-blog-header1.jpg' %}"
              alt="Author's Image"
            />
          </div>

          <div class="blog-author-text">
            <p>{{post.author}}</p>
            <p>Apr 15 - 3 Min</p>
          </div>
        </div>

        <div class="blog-content">
          <a href="/blog/{{post.category}}/{{post.slug}}" style="color: black"
            ><h2 class="md-heading">{{post.title}}</h2></a
          >
          <div class = "preview" style="min-height:90px; font-size: 17px;">{{post.content|safe|truncatechars:200}}</div>

          <div class="hr-bottom"></div>

          <div class="views-comment flex">
            <p>4356 Views</p>
            <p><a href="/blog/{{post.category}}/{{post.slug}}#comment-b">Write a comment</a></p>
          </div>
        </div>
      </div>
    </div>

    {% endif %}
    {% endfor %}
  </div>
</div>

<script>
  preview_content = document.getElementsByClassName("preview")
  Array.from(preview_content).forEach(function(element){
    element.innerHTML = element.innerText
  })
</script>
{% endblock body %}

templates/blog/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard - YourBlog{% endblock title %}

{% block body %}

<div class="container">
    <h1 class="lg-heading text-center">Dashboard</h1>

    <div class="dashboard-div">
        <div class="table-div">
            <table style="width: 100%; margin-top: 30px;">
                <tr>
                    <th>S.no</th>
                    <th>Posts</th>
                    <th>Actions</th>
                </tr>
                {% for post in posts %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{post.title}}</td>
                    <td><a href="/editPost/{{post.serial_no}}" ><button type="button" class="btn btn-dash">Edit</button></a> <a href="/deletePost/{{post.slug}}" ><button type="button"
                            class="btn btn-dash">Delete</button></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="add-post-btn text-center">
            <a href="/editPost/0"><button type="button" class="btn">Add New Post</button></a>
        </div>
    </div>
</div>

{% endblock body %}

templates/blog/editPost.html
{% extends 'base.html' %}

{% block title %} Edit Post - {{post.title}}{% endblock title %}

{% block body %}
<div class="container">
    <h1 class="lg-heading text-center">Edit Post</h1>
    <form action="/editPost/{{serial_no}}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="editForm flex-column">
        <input type="text" name="title" placeholder="Title" value="{{post.title}}">

        <input type="text" name="tagline" placeholder="Tagline" value="{{post.tagline}}">

        <input type="slug" name="slug" placeholder="Slug" value="{{post.slug}}">

        <input type="text" class="category-input" name="category" placeholder="category" value="{{post.category}}">

        {{ form.image}}

        <label for="id_image">Choose a Post Thumbnail <span><i class="	fas fa-camera-retro"></i></span></label>

        <textarea name="content" id="editTextarea" cols="30" rows="10" placeholder="Content">{{post.content}}</textarea>

        <div class="submit-btn">
        <button type="submit" class="btn"> Edit </button>
    </div>
    </div>
    </form>
</div>

<script>
    tinymce.init({
        selector: '#editTextarea',
        height: 500,
        menubar: false,
        plugins: [
            'advlist autolink link image lists charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
            'table emoticons template paste help'
          ],
          toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
            'bullist numlist outdent indent | link image | print preview media fullpage | ' +
            'forecolor backcolor emoticons | help',
          menu: {
            favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons'}
          },
          menubar: 'favs file edit view insert format tools table help',
          content_css: 'css/content.css'
        });
</script>
{% endblock body %}

templates/blog/post.html
{% extends 'base.html' %}

{% block title %} {{post.title|slice:":-1"}} - YourBlog {% endblock title %}

{% block body %}

{% load extras %}

<div class="container">
    <div class="blog-post-content-div">

        <div class="post-title-tagline-div">
            <h1 class="lg-heading">{{post.title}}</h1>
            <h3 class="sm-heading">{{post.tagline}}</h3>
        </div>

        <div class="post-header-image">
            <img src="{{post.thumbnail_image}}" alt="{{post.title}} Header image">
        </div>

        <div class="post-content-by-tinymce">
            {{post.content|safe}}
        </div>

        <div class="post-hr"></div>

        <div class="below-post-hr flex">

            <div class="social-icons">
                <i class="fab fa-facebook-f fa-2x icon"></i>
                <i class="fab fa-twitter fa-2x icon"></i>
                <i class="fab fa-instagram fa-2x icon"></i>
            </div>

            <div class="category-h3 sm-heading">Category : <span
                    style="color: grey; font-size: 18px;">{{post.category|title}}</span></div>
        </div>

        <div class="post-hr" style="margin-top: 10px; margin-bottom: 30px;"></div>

        {% if user.is_authenticated %}
        <div class="comment-section" id="comment-b" style="margin-top: 25px;">
            <div class="comment-box flex-column-no-center">
                <form action="/blog/postComment" method="POST">{% csrf_token %}
                    <h2 class="md-heading text-left">Leave a comment :</h2>
                    <textarea class="comment-textarea" name="comment-textarea" id="" cols="30" rows="10"></textarea>
                    <input type="hidden" name="postSerial" value="{{post.serial_no}}">
                    <input type="hidden" name="parentSerial" value="">
                    <button type="submit" class="btn-primary comment-submit" id="">Submit</button>
                </form>
            </div>
        </div>

        {% else %}

        <h2 class="md-heading">You have to be logged in to Post Comments !!</h2>

        {% endif %}

        <div class="post-hr" style="margin-bottom: 20px;"></div>

        <div class="md-heading" style="margin-bottom: 30px;">Comments (0)</div>


    </div>

    {% for comment in comments %}
    <div class="comment-reply-div flex">
        <div class="comment-user-img">
            <img src="/media/{{post.thumbnail_image}}" alt="" style="width: 50px; height: 50px; border-radius: 100%;">
        </div>

        <div class="comment-show flex-column-no-center" style="margin-left: 25px; width: 100%;">
            <h2 class="sm-heading">{{comment.user.username}}</h2>
            <p class="comment-timestamp">{{comment.timestamp}}</p>
            <p class="comment-text">{{comment.comment}}</p>

            {% if user.is_authenticated %}
            <button type="button" class="btn-primary reply-submit" id="reply-btn">Reply</button>
            {% endif %}

            <div class="comment-section" id="reply-box" style="margin-top: 25px; display: none; border: 1px solid lightgray; padding: 10px;">
                <div class="reply border comment-box flex-column-no-center">
                    <form action="/blog/postComment" method="POST">{% csrf_token %}
                        <h2 class="md-heading text-left">Reply</h2>
                        <textarea class="comment-textarea" name="comment-textarea" id="" cols="30" rows="10"></textarea>
                        <input type="hidden" name="postSerial" value="{{post.serial_no}}">
                        <input type="hidden" name="parentSerial" value="{{comment.serial_no}}">
                        <button type="submit" class="reply-submit btn-primary comment-submit" id="">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Reply Show -->

    {% for reply in replyDict|get_val:comment.serial_no %}
    <div class="reply-div" id="reply-b{{comment.serial_no}}" style="margin-left: 45px;">
        <div class="comment-reply-div flex">
            <div class="comment-user-img">
                <img src="{{post.thumbnail_image}}" alt=""
                    style="width: 50px; height: 50px; border-radius: 100%;">
            </div>

            <div class="comment-show flex-column-no-center" style="margin-left: 25px;">
                <h2 class="sm-heading">{{reply.user.username}}</h2>
                <p class="comment-timestamp">{{reply.timestamp}}</p>
                <p class="comment-text">{{reply.comment}}</p>
            </div>
        </div>
    </div>

    {% endfor %}

    {% endfor %}

</div>

{% block js %}

<script>
    let acc = document.getElementsByClassName("reply-submit");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    /* Toggle between adding and removing the "active" class,
    to highlight the button that controls the panel */

    /* Toggle between hiding and showing the active panel */
    var panel = this.nextElementSibling;
    console.log(panel.style.display);
    if (panel.style.display === "none") {
        panel.style.display = "block";
    }
    else{
        panel.style.display = "none";
    }
  });
}
</script>

{% endblock js %}

{% endblock body %}